/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_Indication_SWC_.c
 * Generated on: Mon Nov 6 22:48:5 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorLock_Indication_SWC.h"

Rte_DE_myuint8 ReadDoorSensor_PP_SR_DoorState;
Rte_DE_myuint8 DoorLock_indication_RP_SR_DoorState_DoorState;


const Rte_CDS_DoorLock_Indication_SWC Rte_Instance_DoorLock_Indication_SWC = {
&DoorLock_indication_RP_SR_DoorState_DoorState
};

const Rte_CDS_DoorLock_Indication_SWC * const Rte_Inst_DoorLock_Indication_SWC = &Rte_Instance_DoorLock_Indication_SWC;


Std_ReturnType DoorLock_Indication_SWC_RP_CS_Led_Switch_LED_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_Indication_SWC_RP_CS_Led_Switch_LED_Switch Rte_Call_DoorLock_Indication_SWC_RP_CS_Led_Switch_LED_Switch_Delegate = 0;

myuint8 Rte_IRead_DoorLock_Indication_SWC_DoorLock_indication_RP_SR_DoorState_DoorState (void)
{
	return (Rte_Inst_DoorLock_Indication_SWC)->DoorLock_indication_RP_SR_DoorState_DoorState->value;
}
Std_ReturnType Rte_Call_DoorLock_Indication_SWC_RP_CS_Led_Switch_LED_Switch (myuint8 LedState)
{
	Std_ReturnType __result = DoorLock_Indication_SWC_RP_CS_Led_Switch_LED_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_Indication_SWC_RP_CS_Led_Switch_LED_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_Indication_SWC_RP_CS_Led_Switch_LED_Switch_Delegate(LedState);
	}
	/* Synchronous implementation to call direct runnable (operation) */
	Led_Switch_Runnable(LedState);
	return __result;
}
